module.exports = {

	// client_id:client_secret
	// encoded - generated by postman
	authString: "MG9hY2UzdDhyYlpUcnA4amkwaDc6cXZNcjl5ODdZa19jTEdWZnJvdjBUU1E5dGpGMmJfb0lFX0MwSFlxNQ==",
	oktaTenant: "https://partnerpoc.oktapreview.com",
	// authServerID: "ausce8ii5wBzd0zvQ0h7",
	clientID: "0oac7c9f6goG9x3FY0h7",
	redirect_uri: "http://localhost:3068",
	proxy_uri: "http://okta-solar-system.cloudhub.io",
}