#%RAML 0.8
title: Okta API Access Management - Solar System sample proxy
version: 01
baseUri: https://okta-solar-system.herokuapp.com

securitySchemes:
  - oauth_2_0:
      description: |
        This API supports OAuth 2.0 for authenticating all API requests.
      type: OAuth 2.0
      describedBy:
        headers:
          Authorization:
            description: |
               Used to send a valid OAuth 2 access token. Do not use with the "access_token" query
               string parameter.
            type: string
        queryParameters:
          access_token:
            description: |
               Used to send a valid OAuth 2 access token. Do not use together with the "Authorization"
               header
            type: string
        responses:
          401:
            description: |
              Bad or expired token. This can happen if the user or the API revoked or expired an
              access token. To fix, you should re-authenticate the user.
          403:
            description: |
              Bad OAuth request (wrong consumer key, bad nonce, expired timestamp...). Unfortunately,
              re-authenticating the user won't help here.
      settings:
        authorizationUri: https://partnerpoc.oktapreview.com/oauth2/ausce8ii5wBzd0zvQ0h7/v1/authorize
        accessTokenUri: https://partnerpoc.oktapreview.com/oauth2/ausce8ii5wBzd0zvQ0h7/v1/token
        authorizationGrants: ["code","implicit"]

/planets:
 get:
   securedBy: [oauth_2_0]

/moons:
 get:
   securedBy: [oauth_2_0]